version: '3'
services:
  minirpa:
    image: minirpa
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minirpa
    ports:
      - "3000:3000"
    restart: on-failure
    env_file: .env
