
function config_make(serviceName) {
  var str = `CONFIG [com.cplus.ia] 03:59:22.8990 18.03.2021 @ com.cplus.ia.Instance$SessionProvider
  [Message] ${serviceName} error
  [Source] com.cplus.ia.Instance$SessionProvider@160e99e0
  [Thread] IA-Pool-Thread-31 (44)
  [Exception] com.sun.xml.internal.ws.client.ClientTransportException com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput[HttpClientTransport.java<117>] <- com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process[HttpTransportPipe.java<208>] <- com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest[HttpTransportPipe.java<130>] <- com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest[DeferredTransportPipe.java<95>] <- com.sun.xml.internal.ws.api.pipe.Fiber.__doRun[Fiber.java<1121>] <- com.sun.xml.internal.ws.api.pipe.Fiber._doRun[Fiber.java<1035>] <- com.sun.xml.internal.ws.api.pipe.Fiber.doRun[Fiber.java<1004>] <- com.sun.xml.internal.ws.api.pipe.Fiber.runSync[Fiber.java<862>] <- com.sun.xml.internal.ws.client.Stub.process[Stub.java<448>] <- com.sun.xml.internal.ws.client.sei.SEIStub.doProcess[SEIStub.java<178>] <- com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke[SyncMethodHandler.java<93>] <- com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke[SyncMethodHandler.java<77>] <- com.sun.xml.internal.ws.client.sei.SEIStub.invoke[SEIStub.java<147>] <- com.sun.proxy.$Proxy33.initSessionRq <- com.cplus.sdk.fimi.Session$SessionProxyPort.initSessionRq <- com.cplus.sdk.fimi.Session.logon <- com.cplus.ia.Instance$SessionProvider.awaitLogon <- com.cplus.ia.Instance$ApplicationThread.run <- java.lang.Thread.run[Thread.java<748>]
    [Text] HTTP transport error: java.net.ConnectException: Connection refused (Connection refused)
    [Cause] java.net.ConnectException java.net.PlainSocketImpl.socketConnect[PlainSocketImpl.java] <- java.net.AbstractPlainSocketImpl.doConnect[AbstractPlainSocketImpl.java<350>] <- java.net.AbstractPlainSocketImpl.connectToAddress[AbstractPlainSocketImpl.java<206>] <- java.net.AbstractPlainSocketImpl.connect[AbstractPlainSocketImpl.java<188>] <- java.net.SocksSocketImpl.connect[SocksSocketImpl.java<392>] <- java.net.Socket.connect[Socket.java<607>] <- java.net.Socket.connect[Socket.java<556>] <- sun.net.NetworkClient.doConnect[NetworkClient.java<180>] <- sun.net.www.http.HttpClient.openServer[HttpClient.java<463>] <- sun.net.www.http.HttpClient.openServer[HttpClient.java<558>] <- sun.net.www.http.HttpClient.<init>[HttpClient.java<242>] <- sun.net.www.http.HttpClient.New[HttpClient.java<339>] <- sun.net.www.http.HttpClient.New[HttpClient.java<357>] <- sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient[HttpURLConnection.java<1226>] <- sun.net.www.protocol.http.HttpURLConnection.plainConnect0[HttpURLConnection.java<1205>] <- sun.net.www.protocol.http.HttpURLConnection.plainConnect[HttpURLConnection.java<1056>] <- sun.net.www.protocol.http.HttpURLConnection.connect[HttpURLConnection.java<990>] <- sun.net.www.protocol.http.HttpURLConnection.getOutputStream0[HttpURLConnection.java<1340>] <- sun.net.www.protocol.http.HttpURLConnection.getOutputStream[HttpURLConnection.java<1315>] <- com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput[HttpClientTransport.java<104>] <- com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process[HttpTransportPipe.java<208>] <- com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest[HttpTransportPipe.java<130>] <- com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest[DeferredTransportPipe.java<95>] <- com.sun.xml.internal.ws.api.pipe.Fiber.__doRun[Fiber.java<1121>] <- com.sun.xml.internal.ws.api.pipe.Fiber._doRun[Fiber.java<1035>] <- com.sun.xml.internal.ws.api.pipe.Fiber.doRun[Fiber.java<1004>] <- com.sun.xml.internal.ws.api.pipe.Fiber.runSync[Fiber.java<862>] <- com.sun.xml.internal.ws.client.Stub.process[Stub.java<448>] <- com.sun.xml.internal.ws.client.sei.SEIStub.doProcess[SEIStub.java<178>] <- com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke[SyncMethodHandler.java<93>] <- com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke[SyncMethodHandler.java<77>] <- com.sun.xml.internal.ws.client.sei.SEIStub.invoke[SEIStub.java<147>] <- com.sun.proxy.$Proxy33.initSessionRq <- com.cplus.sdk.fimi.Session$SessionProxyPort.initSessionRq <- com.cplus.sdk.fimi.Session.logon <- com.cplus.ia.Instance$SessionProvider.awaitLogon <- com.cplus.ia.Instance$ApplicationThread.run <- java.lang.Thread.run[Thread.java<748>]
      [Text] Connection refused (Connection refused)`;
  return str;
}

function severe_make(serviceName) {
  var str = `SEVERE [com.cplus.ia] 04:14:16.7460 18.03.2021 @ com.cplus.sdk.ex.Instance$InterfaceListener$2
  [Message] ${serviceName} error
  [Source] Instance:[UnitID:10320;External:{Host:[Protocol:BTPN-MiddleWare (v.1.5);Config:ISO-8583 Based Host Interface]}]
  [Thread] IA-Pool-Thread-106 (119)
  [Exception] com.cplus.sdk.ex.ProcessorException com.btpn.alibaba.InterfaceMiddleware.handle[InterfaceMiddleware.java<242>] <- com.cplus.sdk.iso.Processor.process <- com.cplus.sdk.iso.Module.process <- com.cplus.ia.Instance$InterfaceListener$2.run <- java.util.concurrent.Executors$RunnableAdapter.call[Executors.java<511>] <- java.util.concurrent.FutureTask.run[FutureTask.java<266>] <- java.util.concurrent.ThreadPoolExecutor.runWorker[ThreadPoolExecutor.java<1149>] <- java.util.concurrent.ThreadPoolExecutor$Worker.run[ThreadPoolExecutor.java<624>] <- com.cplus.ia.Instance$ApplicationThread.run <- java.lang.Thread.run[Thread.java<748>]
    [Text] Unhandled processing error
    [Cause] com.cplus.sdk.ex.ProcessorException com.btpn.alibaba.InterfaceMiddleware.onNetwork[InterfaceMiddleware.java<639>] <- com.btpn.alibaba.InterfaceMiddleware.handle[InterfaceMiddleware.java<153>] <- com.cplus.sdk.iso.Processor.process <- com.cplus.sdk.iso.Module.process <- com.cplus.ia.Instance$InterfaceListener$2.run <- java.util.concurrent.Executors$RunnableAdapter.call[Executors.java<511>] <- java.util.concurrent.FutureTask.run[FutureTask.java<266>] <- java.util.concurrent.ThreadPoolExecutor.runWorker[ThreadPoolExecutor.java<1149>] <- java.util.concurrent.ThreadPoolExecutor$Worker.run[ThreadPoolExecutor.java<624>] <- com.cplus.ia.Instance$ApplicationThread.run <- java.lang.Thread.run[Thread.java<748>]
      [Text] Network message processing error.
      [Cause] com.cplus.sdk.ex.NetworkException com.cplus.sdk.iso.Module.force <- com.btpn.alibaba.InterfaceMiddleware.onNetwork[InterfaceMiddleware.java<611>] <- com.btpn.alibaba.InterfaceMiddleware.handle[InterfaceMiddleware.java<153>] <- com.cplus.sdk.iso.Processor.process <- com.cplus.sdk.iso.Module.process <- com.cplus.ia.Instance$InterfaceListener$2.run <- java.util.concurrent.Executors$RunnableAdapter.call[Executors.java<511>] <- java.util.concurrent.FutureTask.run[FutureTask.java<266>] <- java.util.concurrent.ThreadPoolExecutor.runWorker[ThreadPoolExecutor.java<1149>] <- java.util.concurrent.ThreadPoolExecutor$Worker.run[ThreadPoolExecutor.java<624>] <- com.cplus.ia.Instance$ApplicationThread.run <- java.lang.Thread.run[Thread.java<748>]
        [Cause] java.nio.channels.ClosedChannelException com.cplus.sdk.net.Client.write <- com.cplus.sdk.iso.Module$ModuleTCP.sendMessage <- com.cplus.sdk.iso.Module.force <- com.btpn.alibaba.InterfaceMiddleware.onNetwork[InterfaceMiddleware.java<611>] <- com.btpn.alibaba.InterfaceMiddleware.handle[InterfaceMiddleware.java<153>] <- com.cplus.sdk.iso.Processor.process <- com.cplus.sdk.iso.Module.process <- com.cplus.ia.Instance$InterfaceListener$2.run <- java.util.concurrent.Executors$RunnableAdapter.call[Executors.java<511>] <- java.util.concurrent.FutureTask.run[FutureTask.java<266>] <- java.util.concurrent.ThreadPoolExecutor.runWorker[ThreadPoolExecutor.java<1149>] <- java.util.concurrent.ThreadPoolExecutor$Worker.run[ThreadPoolExecutor.java<624>] <- com.cplus.ia.Instance$ApplicationThread.run <- java.lang.Thread.run[Thread.java<748>]`;
  return str;
}

export { severe_make, config_make };
